# Generated by Django 4.0.6 on 2022-08-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, to='service_scheduler.service', verbose_name='Specializations'),
        ),
    ]
