# Generated by Django 4.0.6 on 2022-08-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_scheduler', '0002_alter_profile_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='service_scheduler.profile', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_sessions', to='service_scheduler.profile', verbose_name='Provider'),
        ),
    ]
